FROM golang:1.22-alpine AS builder
RUN apk add --no-cache git
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.24.1

FROM alpine:3.19
RUN apk add --no-cache ca-certificates tzdata postgresql-client
COPY --from=builder /go/bin/goose /usr/local/bin/goose

CMD ["goose", "--help"]
