// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lessons.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllLessons = `-- name: CountAllLessons :one
SELECT COUNT(*)
FROM lessons
`

func (q *Queries) CountAllLessons(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllLessons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLessonsByUserID = `-- name: CountLessonsByUserID :one
SELECT COUNT(*)
FROM lessons
WHERE user_id = $1
`

func (q *Queries) CountLessonsByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLessonsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (
    user_id, title, target_language, source_language, total_words, duration_sec,
    pacing_config, transcript_chunks, audio_file_path, srt_file_path, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, title, status, created_at
`

type CreateLessonParams struct {
	UserID           pgtype.UUID    `json:"user_id"`
	Title            string         `json:"title"`
	TargetLanguage   string         `json:"target_language"`
	SourceLanguage   pgtype.Text    `json:"source_language"`
	TotalWords       pgtype.Int4    `json:"total_words"`
	DurationSec      pgtype.Numeric `json:"duration_sec"`
	PacingConfig     []byte         `json:"pacing_config"`
	TranscriptChunks []byte         `json:"transcript_chunks"`
	AudioFilePath    string         `json:"audio_file_path"`
	SrtFilePath      string         `json:"srt_file_path"`
	Status           string         `json:"status"`
}

type CreateLessonRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (CreateLessonRow, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.UserID,
		arg.Title,
		arg.TargetLanguage,
		arg.SourceLanguage,
		arg.TotalWords,
		arg.DurationSec,
		arg.PacingConfig,
		arg.TranscriptChunks,
		arg.AudioFilePath,
		arg.SrtFilePath,
		arg.Status,
	)
	var i CreateLessonRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLesson = `-- name: DeleteLesson :exec
DELETE FROM lessons
WHERE id = $1
`

func (q *Queries) DeleteLesson(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLesson, id)
	return err
}

const getLearningProgress = `-- name: GetLearningProgress :one
SELECT user_id, lesson_id, playback_offset_sec, shadowing_repeat_count, is_completed, version, last_listened_at
FROM learning_progress
WHERE user_id = $1 AND lesson_id = $2 LIMIT 1
`

type GetLearningProgressParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	LessonID pgtype.UUID `json:"lesson_id"`
}

type GetLearningProgressRow struct {
	UserID               pgtype.UUID        `json:"user_id"`
	LessonID             pgtype.UUID        `json:"lesson_id"`
	PlaybackOffsetSec    pgtype.Numeric     `json:"playback_offset_sec"`
	ShadowingRepeatCount pgtype.Int4        `json:"shadowing_repeat_count"`
	IsCompleted          pgtype.Bool        `json:"is_completed"`
	Version              pgtype.Int4        `json:"version"`
	LastListenedAt       pgtype.Timestamptz `json:"last_listened_at"`
}

func (q *Queries) GetLearningProgress(ctx context.Context, arg GetLearningProgressParams) (GetLearningProgressRow, error) {
	row := q.db.QueryRow(ctx, getLearningProgress, arg.UserID, arg.LessonID)
	var i GetLearningProgressRow
	err := row.Scan(
		&i.UserID,
		&i.LessonID,
		&i.PlaybackOffsetSec,
		&i.ShadowingRepeatCount,
		&i.IsCompleted,
		&i.Version,
		&i.LastListenedAt,
	)
	return i, err
}

const getLessonByID = `-- name: GetLessonByID :one
SELECT id, user_id, title, target_language, source_language, total_words, duration_sec,
       pacing_config, transcript_chunks, audio_file_path, srt_file_path, status, created_at, updated_at
FROM lessons
WHERE id = $1 LIMIT 1
`

type GetLessonByIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Title            string             `json:"title"`
	TargetLanguage   string             `json:"target_language"`
	SourceLanguage   pgtype.Text        `json:"source_language"`
	TotalWords       pgtype.Int4        `json:"total_words"`
	DurationSec      pgtype.Numeric     `json:"duration_sec"`
	PacingConfig     []byte             `json:"pacing_config"`
	TranscriptChunks []byte             `json:"transcript_chunks"`
	AudioFilePath    string             `json:"audio_file_path"`
	SrtFilePath      string             `json:"srt_file_path"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetLessonByID(ctx context.Context, id pgtype.UUID) (GetLessonByIDRow, error) {
	row := q.db.QueryRow(ctx, getLessonByID, id)
	var i GetLessonByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.TargetLanguage,
		&i.SourceLanguage,
		&i.TotalWords,
		&i.DurationSec,
		&i.PacingConfig,
		&i.TranscriptChunks,
		&i.AudioFilePath,
		&i.SrtFilePath,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllLessons = `-- name: ListAllLessons :many
SELECT id, user_id, title, target_language, source_language, total_words, duration_sec,
       pacing_config, transcript_chunks, audio_file_path, srt_file_path, status, created_at, updated_at
FROM lessons
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllLessonsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllLessonsRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Title            string             `json:"title"`
	TargetLanguage   string             `json:"target_language"`
	SourceLanguage   pgtype.Text        `json:"source_language"`
	TotalWords       pgtype.Int4        `json:"total_words"`
	DurationSec      pgtype.Numeric     `json:"duration_sec"`
	PacingConfig     []byte             `json:"pacing_config"`
	TranscriptChunks []byte             `json:"transcript_chunks"`
	AudioFilePath    string             `json:"audio_file_path"`
	SrtFilePath      string             `json:"srt_file_path"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAllLessons(ctx context.Context, arg ListAllLessonsParams) ([]ListAllLessonsRow, error) {
	rows, err := q.db.Query(ctx, listAllLessons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllLessonsRow
	for rows.Next() {
		var i ListAllLessonsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.TargetLanguage,
			&i.SourceLanguage,
			&i.TotalWords,
			&i.DurationSec,
			&i.PacingConfig,
			&i.TranscriptChunks,
			&i.AudioFilePath,
			&i.SrtFilePath,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsByUserID = `-- name: ListLessonsByUserID :many
SELECT id, user_id, title, target_language, source_language, total_words, duration_sec,
       pacing_config, transcript_chunks, audio_file_path, srt_file_path, status, created_at, updated_at
FROM lessons
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLessonsByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListLessonsByUserIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Title            string             `json:"title"`
	TargetLanguage   string             `json:"target_language"`
	SourceLanguage   pgtype.Text        `json:"source_language"`
	TotalWords       pgtype.Int4        `json:"total_words"`
	DurationSec      pgtype.Numeric     `json:"duration_sec"`
	PacingConfig     []byte             `json:"pacing_config"`
	TranscriptChunks []byte             `json:"transcript_chunks"`
	AudioFilePath    string             `json:"audio_file_path"`
	SrtFilePath      string             `json:"srt_file_path"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListLessonsByUserID(ctx context.Context, arg ListLessonsByUserIDParams) ([]ListLessonsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listLessonsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLessonsByUserIDRow
	for rows.Next() {
		var i ListLessonsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.TargetLanguage,
			&i.SourceLanguage,
			&i.TotalWords,
			&i.DurationSec,
			&i.PacingConfig,
			&i.TranscriptChunks,
			&i.AudioFilePath,
			&i.SrtFilePath,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLessonRenderResult = `-- name: UpdateLessonRenderResult :one
UPDATE lessons
SET status = $2,
    audio_file_path = $3,
    srt_file_path = $4,
    duration_sec = $5,
    transcript_chunks = $6,
    total_words = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, title, status, audio_file_path, srt_file_path, duration_sec, updated_at
`

type UpdateLessonRenderResultParams struct {
	ID               pgtype.UUID    `json:"id"`
	Status           string         `json:"status"`
	AudioFilePath    string         `json:"audio_file_path"`
	SrtFilePath      string         `json:"srt_file_path"`
	DurationSec      pgtype.Numeric `json:"duration_sec"`
	TranscriptChunks []byte         `json:"transcript_chunks"`
	TotalWords       pgtype.Int4    `json:"total_words"`
}

type UpdateLessonRenderResultRow struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	Status        string             `json:"status"`
	AudioFilePath string             `json:"audio_file_path"`
	SrtFilePath   string             `json:"srt_file_path"`
	DurationSec   pgtype.Numeric     `json:"duration_sec"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateLessonRenderResult(ctx context.Context, arg UpdateLessonRenderResultParams) (UpdateLessonRenderResultRow, error) {
	row := q.db.QueryRow(ctx, updateLessonRenderResult,
		arg.ID,
		arg.Status,
		arg.AudioFilePath,
		arg.SrtFilePath,
		arg.DurationSec,
		arg.TranscriptChunks,
		arg.TotalWords,
	)
	var i UpdateLessonRenderResultRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.AudioFilePath,
		&i.SrtFilePath,
		&i.DurationSec,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLessonStatus = `-- name: UpdateLessonStatus :exec
UPDATE lessons
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateLessonStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateLessonStatus(ctx context.Context, arg UpdateLessonStatusParams) error {
	_, err := q.db.Exec(ctx, updateLessonStatus, arg.ID, arg.Status)
	return err
}

const upsertLearningProgress = `-- name: UpsertLearningProgress :exec
INSERT INTO learning_progress (
    user_id, lesson_id, playback_offset_sec, shadowing_repeat_count, is_completed, version
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (user_id, lesson_id) DO UPDATE SET
    playback_offset_sec = EXCLUDED.playback_offset_sec,
    shadowing_repeat_count = EXCLUDED.shadowing_repeat_count,
    is_completed = EXCLUDED.is_completed,
    version = learning_progress.version + 1,
    last_listened_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertLearningProgressParams struct {
	UserID               pgtype.UUID    `json:"user_id"`
	LessonID             pgtype.UUID    `json:"lesson_id"`
	PlaybackOffsetSec    pgtype.Numeric `json:"playback_offset_sec"`
	ShadowingRepeatCount pgtype.Int4    `json:"shadowing_repeat_count"`
	IsCompleted          pgtype.Bool    `json:"is_completed"`
	Version              pgtype.Int4    `json:"version"`
}

func (q *Queries) UpsertLearningProgress(ctx context.Context, arg UpsertLearningProgressParams) error {
	_, err := q.db.Exec(ctx, upsertLearningProgress,
		arg.UserID,
		arg.LessonID,
		arg.PlaybackOffsetSec,
		arg.ShadowingRepeatCount,
		arg.IsCompleted,
		arg.Version,
	)
	return err
}
