// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type LearningProgress struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	LessonID             pgtype.UUID        `json:"lesson_id"`
	PlaybackOffsetSec    pgtype.Numeric     `json:"playback_offset_sec"`
	ShadowingRepeatCount pgtype.Int4        `json:"shadowing_repeat_count"`
	IsCompleted          pgtype.Bool        `json:"is_completed"`
	Version              pgtype.Int4        `json:"version"`
	LastListenedAt       pgtype.Timestamptz `json:"last_listened_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Lesson struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Title            string             `json:"title"`
	TargetLanguage   string             `json:"target_language"`
	SourceLanguage   pgtype.Text        `json:"source_language"`
	TotalWords       pgtype.Int4        `json:"total_words"`
	DurationSec      pgtype.Numeric     `json:"duration_sec"`
	PacingConfig     []byte             `json:"pacing_config"`
	TranscriptChunks []byte             `json:"transcript_chunks"`
	AudioFilePath    string             `json:"audio_file_path"`
	SrtFilePath      string             `json:"srt_file_path"`
	Embedding        pgvector.Vector    `json:"embedding"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Status           string             `json:"status"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     pgtype.Text        `json:"full_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserDevice struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	DeviceType string             `json:"device_type"`
	PushToken  string             `json:"push_token"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
